### ISSUE TITLE
method slickGoTo doesn't work in 1.5

### ISSUE THREAD

**Issue by zolem** [kenwheeler/slick#1677]
I have been using 1.3 on another website and using slickGoTo without any problems. I recently implemented slick trying to get that function to work for hours and it kept saying "slickGoTo is not a function".

I assumed the slick object just wasn't getting created and kept trying to figure out why. Finally I thought that maybe its the version. I included the slick.min.js from the original website and everything worked fine. Something is wrong with 1.5 where the function slickGoTo simply doesn't exist.

Did I miss an update that removed or changed the call on this functionality? Any help would be appreciated. Thanks!

**Comment by pmantzar** [comment]
Can you paste the JS you wrote?
I currently use slickGoTO with on(click) and on(afterChange) on linked slideshows.

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown

**Comment by zolem** [comment]
Here is a fiddle where I got the problem to appear: https://jsfiddle.net/rrg3/jrj3tgfv/2/
Here is a fiddle where it works fine in an older version: https://jsfiddle.net/rrg3/h9pxg61h/
