### ISSUE TITLE
Slick 1.9.0 script tag is not loading

### ISSUE THREAD

**Issue by GustavoRSSilva** [kenwheeler/slick#3477]
cdn.jsdelivr.net/gh/kenwheeler/slick@1.9.0/slick/slick.min.js  returns an error.

====================================================================

#### Steps to reproduce the problem

```html
<!-- Add the slick-theme.css if you want default styling -->
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.9.0/slick/slick.css"/>
<!-- Add the slick-theme.css if you want default styling -->
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.9.0/slick/slick-theme.css"/>
```

Then, before your closing ```<body>``` tag add:

```html
<script type="text/javascript" src="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.9.0/slick/slick.min.js"></script>
```

====================================================================

#### What is the expected behaviour?

the library should be loaded, instead there is this error.

$(...).slick() is not a function.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Chrome - Version 67.0.3396.62 (Official Build) (64-bit)

- Which jQuery/Slick version are you using?
1.9, it works with 1.8

- Did this work before?
I don't know, probably stopped working at some time. This is the first time i tried.

**Comment by GustavoRSSilva** [comment]
Downgrading to the version 1.8 made it work.

**Comment by failtus** [comment]
@GustavoRSSilva  v1.9.0 has not release yet. 

You can check official release list on [this link](https://github.com/kenwheeler/slick/releases)

**Comment by GustavoRSSilva** [comment]
@failtus I was just following the read.me

![screenshot from 2018-07-06 14-59-50](https://user-images.githubusercontent.com/8384988/42382802-461ead82-812d-11e8-99d4-235ec1ccd91a.png)


As you can see is it point to the 1.9.0 version. It is misleading.

**Comment by failtus** [comment]
@GustavoRSSilva Yes, it is.
You can use this one. ` https://cdnjs.com/libraries/slick-carousel`

**Comment by Zulcom** [comment]
Awesome beginner tip: include this lib by URL that returns 404.
Nice guide. 
The developer hints at the start that bugs in the documentation are fully guaranteed
Many thanks to developer.

**Comment by adelinyshka** [comment]
still get this message in js console:
![11](https://user-images.githubusercontent.com/35169516/57622863-2a32e200-7597-11e9-8a43-42c43e5c64d4.png)

Do I understand right that I should use **just** **https://cdnjs.com/libraries/slick-carousel**
but **not both** links as written in documentation?

**Comment by ahmadalfy** [comment]
We’re pushing 1.9.0 to NPM shortly. My apologies for that.

**Comment by ahmadalfy** [comment]
I checked with @kenwheeler. Apparently 1.9 had a lot of bugs so he pulled it off NPM. I will revert the documentation
