### ISSUE TITLE
Public methods are not accessible; not a function

### ISSUE THREAD

**Issue by rossthedevigner** [kenwheeler/slick#1356]
I cannot call the public methods in version 1.5.0

"Uncaught TypeError: slider.slickPause is not a function"
"Uncaught TypeError: slider.slickPlay is not a function"

Version 1.5.0
http://jsfiddle.net/bu94scu3/2/

It works in 1.3.2
http://jsfiddle.net/bu94scu3/3/

**Comment by francescobonomi** [comment]
Commenting here as this is the first search result for slickPlay is not a function. and it's easy to get lost in such a simple issue
Since version 1.4.0, the way to call all methods is:

`$("#something").slick('slickPlay');`

and no longer

`$("#something").slickPlay();`
