### ISSUE TITLE
TypeError after updating to 1.5.8

### ISSUE THREAD

**Issue by solenoo** [kenwheeler/slick#1873]
After i've updated to 1.5.8 from 1.5.7, I started getting this error in my browser "TypeError: jQuery.easing[this.easing] is not a function"

**Comment by solenoo** [comment]
NVM i noticed you've changed the easing my bad :)
